### ISSUE TITLE
KQ2: Menu, status and input line do not come back after SQ1 promo

### ISSUE THREAD

**Issue by lanceewing** [lanceewing/agile#13]
Also, the menu shortcut keys don't work either.

**Comment by lanceewing** [comment]
It is basically unusable. The only thing active is the ability to walk around rooms. No other input.

**Comment by vafada** [comment]
logic57 has

```
if (vPreviousRoom == 117)
        {
            status.line.on();
            accept.input();
            reset(f189);
            load.view(0);
            set.view(oEgo,0);
            position.v(oEgo,v116,v117);
            set.loop.v(oEgo,v118);
            set(f30);
        }
```

the room with the hole is 57

the sq2 promo is room  110 to 117

but when leaving the sq2 promo animation.. prev room flag has 110 (which is the first room of the sq2 promo
