### ISSUE TITLE
KQ2: When falling off dwarf house ladder, ego gets stuck tumbling

### ISSUE THREAD

**Issue by lanceewing** [lanceewing/agile#14]
Not sure if this would have happened in the original, but when falling off the ladder, and ego starts tumbling, he gets stuck in an endless tumble towards the bottom and never hits the ground.

**Comment by vafada** [comment]
It happens on the Steam King Question Collection

Exact spot where it happens:

![Capture](https://user-images.githubusercontent.com/285941/198464794-8d3362ea-a050-4799-a6d5-803a8246d1af.PNG)

from there just move left

**Comment by lanceewing** [comment]
Yeah, you are right, I tried that and the same thing happens in the original game. This is from Dosbox:

![image](https://user-images.githubusercontent.com/8688804/198752255-1f8e525a-a885-4470-895b-08ad114d3ea5.png)

**Comment by lanceewing** [comment]
Closing, as this also happens in the original game.
