### ISSUE TITLE
Saved game files for AGI V3

### ISSUE THREAD

**Issue by lanceewing** [lanceewing/agile#33]
WinAGI claims the following:
> In version 3 games, the OBJECT file is encrypted before being added to the save game file.

AGILE isn't doing this at the moment, so that implies that V3 saved games won't work when loaded into the original V3 AGI interpreter. This would apply to KQ4 AGI, Gold Rush, the Manhunter games, and the V3 AGI version of Black Cauldron.

**Edit:**

Expanding the scope of this Issue to include all AGI V3 saved game requirements. This currently includes:

- The encryption of the OBJECT section, as described above.
- Only 12 strings for version 3.002.149.
- Save variables section (first part) of saved game file has 3 additional bytes for versions 3.002.102, 3.002.107 and 3.002.149. Their use is currently unknown, but could be related to the new commands. Regardless, we need to adjust for the extra size.

**Comment by lanceewing** [comment]
To determine if the game is an AGI V3 game, we can use the v3GameSig field in the Game object, as that field will only be set for V3 games, so is a good way to recognise all V3 interpreter versions, regardless of whether there is an AGIDATA.OVL file in the game folder or not, i.e. the v3GameSig field should "trump" the version field with regards to detecting a V3 game.

**Comment by vafada** [comment]
`state.Objects.Encode()` in AGILibrary does `Crypt()` before returning the byte array if `Crypted` is true.... is this the same encryption? I cannot see when `Crypted` is set to `true`

```
byte[] array = memoryStream.ToArray();
                if (Crypted)
                {
                    Crypt(array, 0, array.Length);
                }

                return array;
```

**Comment by lanceewing** [comment]
Yes. AGILE doesn't retain the original value for Crypted. When the AGILibrary loads the OBJECT file, then initially Crypted is set to a value depending on whether the OBJECT file was encrypted or not. AGILE doesn't retain that, and in fact it doesn't need it, since it doesn't need to touch the original file again. You'll see that it makes a copy in the GameState Init method, and the copy leaves Crypted as the default false.

The versions in which the OBJECT file itself is encrypted is different than the versions in which the OBJECT section in the saved game files is encrypted.

We could either set Crypted to true before calling Encode, or (maybe cleaner) is to use the copy constructor to create a new Objects instance with the crypted parameter passed in with either true or false depending on what the saved game file needs. The "crypted" parameter is optional in the copy constructor.

**Comment by lanceewing** [comment]
I have changes to the SavedGames class that will now work with AGI V3 saved games. I have tested it with GR and MH2 so far. I think I will push the changes already, but will continue testing. It involved some refactoring that could impact other AGI interpreter versions, but hopefully everything in that area continues to work.

**Comment by lanceewing** [comment]
I have now testing in KQ4 AGI, with both saving from AGILE and loading in the original AGI interpreter, and saving in the original AGI interpreter and loading in KQ4. The AGI interpreter version is: 3.002.086.

**Comment by lanceewing** [comment]
@vafada , let me know if you happen to spot any new issues in the save game area, as they may be related to my recent refactoring. Hopefully I have everything covered though from a backwards compatibility perspective.

**Comment by lanceewing** [comment]
Closing. If we find any problems with the implementation later on, then we can raise specific issues for them.
