### ISSUE TITLE
Make saved game "pushed position within script event list" field conditional on version

### ISSUE THREAD

**Issue by lanceewing** [lanceewing/agile#35]
The "pushed position within the script event list" depends on AGI interpreter version:

        // [1505] 1536(2 bytes) Stores a pushed position within the script event list
        // Note: Depends on interpreter version. 2.4xx and below didn't have push.script/pop.script, so they didn't have this saved game field.
        savedGameData[1536] = (byte)(state.ScriptBuffer.SavedScript);

At the moment, there isn't a condition around that in AGILE, so there will be a field present that AGI Interpreters before 2.9xx are not expecting.

This field was not present prior to the inclusion of the push.script() and pop.script() commands, which were included in 2.9xx

**Note:** AGILE's current AGI interpreter version detection is dependent on the original AGI interpreter AGIDATA.OVL file being in the game directory. Many of the AGI fan made games didn't come with the AGI interpreter itself, so in the absence of the AGI interpreter files, we can probably safely assume that the version is at least 2.917, as that was the most common that AGI fans used back in the days when AGI fan made game creation was at its peak. SCUMMVM appears to make the same assumption.

**Comment by vafada** [comment]
related to https://github.com/lanceewing/agile/issues/34#issuecomment-1299368847

**Comment by lanceewing** [comment]
AGILE itself is tolerant with regards to loading 2.4xx vs 2.9xx saved game files. It has this bit:

            if ((postStringsOffset + 20) < aniObjsOffset)
            {
                // [1505] 1536(2 bytes) Stores a pushed position within the script event list
                // Note: Depends on interpreter version. 2.4xx and below didn't have push.script/pop.script, so they didn't have this saved game field.
                state.ScriptBuffer.SavedScript = (savedGameData[postStringsOffset + 20] + (savedGameData[postStringsOffset + 21] << 8));
            }

which checks if the start of the animated objects section hasn't yet begun, and if not, then assumes the pushed script event position is present.

I'm going to put in a check on the SAVE side now for the version, so that AGILE saved games can be loaded into 2.4xx AGI interpreters, e.g. as used in the commonly available KQ2 and LSL versions.

**Comment by lanceewing** [comment]
(V3 saved games, and 2.272 and 2.089 saved games, are a whole other area that will need separate work)

**Comment by lanceewing** [comment]
@vafada , I've just pushed some code to master for this. Games saved from AGILE for KQ2 should now load in the original AGI interpreter for you. I've tried it once myself and it is working, whereas previous the original AGI interpreter was hanging for me. Give it a go and let me know how you get on.

**Comment by vafada** [comment]
confirmed it works... loading KQ2 AGILE save game to Steam then trying to quit doesn't show the empty box anymore...

closing #34

**Comment by lanceewing** [comment]
Thanks for confirming. Closing this one as well.
