### ISSUE TITLE
[PQ1/LSL1] Restore game missing UI component

### ISSUE THREAD

**Issue by vafada** [lanceewing/agile#45]
Agile:

![Capture2](https://user-images.githubusercontent.com/285941/200122108-3d3abf6f-bad5-417b-b1cb-74c75e497463.PNG)

AGI:

![Capture](https://user-images.githubusercontent.com/285941/200122112-48f17bdd-40f7-413e-aac1-127aff34f775.PNG)

in PQ1, during the drive phase, the Map coordinate is shown on the status line. When you save a game while in driving mode and restore that game, the newly restored game doesn't show the map coordinate.

Technical Issue:

At the beginning of Logic 0, on restart game sets `flag 34` to `true`:

```
if (isset(gameRestored))
  {
  set(enableMenu);
  set(f34);
  disable.item(c27);
  if (!isset(f56))
    {
    clear.lines(22, 22, BLACK);
    clear.lines(24, 24, BLACK);
    }
  }
```

at the beginning of Logic 117, it checks if  `flag 34` is set and displays the map coordinate:

```
if (machineType != AMIGA && 
    !isset(f56) && 
    (isset(f34) || 
    isset(newRoom) || 
    controller(c16)))
  {
  reset(f34);
  set.text.attribute(BLACK, WHITE);
  v145 = 0; // row 0 = status line
  v144 = 20; // col 20 = middle
  v152 = 20;
  v152  += currentRoom;
  display.v(v145, v144, v152);
  set.text.attribute(WHITE, BLACK);
  }
```

So in AGILE, it seems to be an order of execution issue. Here's the Debug logs I have:

```
Setting restore to true (state.Flags[Defines.RESTORE] = true in RestoreGameState())`
******************** RESTORE DONE ****************** newRoom = 12 (After loading the file and replaying scripts)
Setting restore to false (state.Flags[Defines.RESTORE] = false in Tick())`
ExecuteLogic logicNum = 0
fRestore = False
ExecuteLogic logicNum = 117
ExecuteLogic logicNum = 96
```

As you can see... even before Logic 0 is called.. the `state.Flags[Defines.RESTORE]` was already set back to false in `Tick()` thus skipping that `if` block on Logic 0 if the game has just been restored

**Comment by vafada** [comment]
[PQSG.zip](https://github.com/lanceewing/agile/files/9943929/PQSG.zip)

save game you can use

**Comment by vafada** [comment]
LSL1 has the same issue.

Screen on restore. Missing bet amount and amount on wallet

![Capture](https://user-images.githubusercontent.com/285941/200133169-21715c2e-2ac1-415f-8412-c411a8ce3132.PNG)

Actual:
![Capture2](https://user-images.githubusercontent.com/285941/200133191-66ca5e3e-07b7-4fa5-b7a1-3b89534837c1.PNG)


Logic 37 is the slot machine room

```
if (isset(gameRestored))
  {
  v207 = 2;
  call(Logic58);
  }
```

Logic 58

```
if (v207 == 2)
  {
  if (monitorType == MONO)
    {
    clear.lines(24, 24, BLACK);
    display(24, 0, "Bet is $%v200.00         You have $%v90.00");
    }
  else
    {
    clear.lines(21, 21, BLACK);
    display(21, 0, "Bet is $%v200.00         You have $%v90.00");
    }
  }
```


The `if (isset(gameRestored))` block is getting evaluated to `false` even though i just restored the game

**Comment by vafada** [comment]
removing this line

https://github.com/lanceewing/agile/blob/46d117b5a409c4ba8c8ca6b9125ffb65b6882b12/AGILE/Commands.cs#L1642

fixes the LSL issue but no PQ...

when I restore the game in PQ... it executes Logic 0 add scanOffet 151

**Comment by lanceewing** [comment]
I've only just read through this, but I think you might be on the right track. It does seem like AGILE is exiting out of the LOGIC evaluating loop too soon. 

The original AGI interpreter does also clear the RESTORE flag at the end of its main loop:

		/* Clear the restart, restore, & init logics flags
		*/
		Reset(INITLOGS);
		Reset(RESTART);
		Reset(RESTORE);

So that implies that the original AGI interpreter does not exit out of its LOGIC evaluation loop as part of a restore but continues scanning the logics.

**Comment by lanceewing** [comment]
Closing, as this appears to be fixed after the NewRoom and logic execution loop refactoring (in #49 )
