### ISSUE TITLE
Broken Views in the final scene of PQ1

### ISSUE THREAD

**Issue by vafada** [lanceewing/agile#52]
The group of polices in the right side seems to be broken

![InkedCapture](https://user-images.githubusercontent.com/285941/201448040-5174cb08-93cb-48b3-9ca2-843770ec2a67.jpg)

Logic 104.

The police are View 154

```
 add.to.pic(View154, 0, 0, 43, 129, 12, 4);
  add.to.pic(View154, 0, 0, 46, 123, 11, 4);
  add.to.pic(View154, 0, 0, 49, 117, 10, 4);
  add.to.pic(View154, 0, 0, 52, 111, 9, 4);
  add.to.pic(View154, 0, 0, 55, 105, 8, 4);
  add.to.pic(View154, 0, 0, 58, 99, 7, 4);
  add.to.pic(View154, 1, 0, 109, 129, 12, 4);
  add.to.pic(View154, 1, 0, 106, 123, 11, 4);
  add.to.pic(View154, 1, 0, 103, 117, 10, 4);
  add.to.pic(View154, 1, 0, 100, 111, 9, 4);
  add.to.pic(View154, 1, 0, 97, 105, 8, 4);
  add.to.pic(View154, 1, 0, 94, 99, 7, 4);
```

I haven't debugged that much

**Comment by vafada** [comment]
I think it has something to do with the transparent pixel and overlapping views.....

If i render just a single view (the cop on x coordinate = 97).. the face is complete

![Capture](https://user-images.githubusercontent.com/285941/201451728-9b037b19-9222-43aa-87ad-66b9c23b7be4.PNG)

but when i render 2 cops (x  coor 97 and 100), the face is incomplete (overlapping views)

![Capture2](https://user-images.githubusercontent.com/285941/201451766-0ccfb106-d29e-46d8-a49f-02cea3790eee.PNG)

**Comment by vafada** [comment]
I also dont understand when showing the priority pixel.. the views on the right side is facing the wrong way:

![Capture3](https://user-images.githubusercontent.com/285941/201451914-1e0022cb-7eb6-43a3-8134-e38d4eb47caa.PNG)

**Comment by vafada** [comment]
also noticed that the blonde man on the lower right also seems to be broken compared to the youtube version

<img width="121" alt="Screen Shot 2022-11-11 at 10 22 45 PM" src="https://user-images.githubusercontent.com/285941/201454227-e6f65411-f5fb-4a04-ae1b-2665f747e7a9.png">

**Comment by lanceewing** [comment]
> I also dont understand when showing the priority pixel.. the views on the right side is facing the wrong way:

I wonder if this might be the main problem and cause. The VIEW resource supports a "mirror" feature. Here it looks like the visual pixels have been "mirrored" but not the priority pixels.

This may be an issue specific to add.to.pics in the mirror mode, as I think we would have noticed if normal animated objects were affected by this. Perhaps add.to.pics are not handling the mirror mode properly.

**Comment by lanceewing** [comment]
Looking at the add.to.pic version of the Draw method, it doesn't look like it supports the mirror mode at all.

**Comment by lanceewing** [comment]
Yeah, I have added support for the mirror mode for add.to.pics in my local code and it has fixed the issue.

I will push it later today.

**Comment by lanceewing** [comment]
@vafada, I have just pushed a fix. Implementing the mirror mode for add.to.pics does appear to have fixed all the issues you mentioned. Can you confirm?

**Comment by vafada** [comment]
fixed! both visual and priority mode
![Capture](https://user-images.githubusercontent.com/285941/201473335-41d049e7-ac6f-4f1c-9cd2-3a80212243cc.PNG)


![Capture2](https://user-images.githubusercontent.com/285941/201473339-0f7031fc-91f5-44b6-bd06-1464630d34c5.PNG)

**Comment by vafada** [comment]
fixed in https://github.com/lanceewing/agile/commit/7210a66eb4b8697b6c10add9f45e322304e343a7
