### ISSUE TITLE
Reusing your original MEKA

### ISSUE THREAD

**Issue by wizardmanannan** [lanceewing/agile#65]
Hi Lance,

I couldn't find a better place to put this, if there is a better way to contact you please advise me.

I started using some of your really old MEKA code from the 90's in a project to run AGI games on CommanderX16 (a new enhanced Commodore 64 ) It isn't on Github as far as I am aware. I intend to Open Source it. 

Someone advised me that though the code is free on the Internet I still legally had to seek permission. 

Do you mind?

Thanks for your time and have a merry Christmas.

**Comment by lanceewing** [comment]
Hi, yeah, that's fine. No worries. I was thinking at one point about putting that code into a GitHub repo but I wrote it so long ago, about 25 years, and I personally am not planning to work further on it. So feel free to put it into your own repo. I'd be quite happy to see it being used as you describe. Running AGI games on a Commodore 64 like machine would be great!

All my effort these days is in AGILE, which is much more complete.

**Comment by wizardmanannan** [comment]
Hi Lance,

Thanks, your code and documentation has made my life so much easier.
